name: geo_fencing_ios
description: "A Flutter plugin for iOS flutter_geofence_manager functionality. Provides background location monitoring and geofence event handling for iOS applications."
version: 1.0.1
homepage: https://github.com/Akshya107/flutter_geo_fencing
repository: https://github.com/Akshya107/flutter_geo_fencing

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  geo_fencing_platform_interface: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: GeoFencingIosPlugin
