name: geo_fencing_platform_interface
description: "A platform interface for geo-fencing plugin."
version: 1.0.1
homepage: https://github.com/Akshya107/flutter_geo_fencing
repository: https://github.com/Akshya107/flutter_geo_fencing

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"


dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter


