name: geo_fencing_android
description: "Android implementation of flutter_geofence_manager plugin."
version: 1.0.2
homepage: https://github.com/Akshya107/flutter_geo_fencing
repository: https://github.com/Akshya107/flutter_geo_fencing


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  geo_fencing_platform_interface: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.geofencing.android
        pluginClass: GeoFencingAndroidPlugin
